DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE USER_INFO ( 
ID INTEGER PRIMARY KEY,
MOBILE_NO BIGINT UNIQUE,
NAME VARCHAR(30),
PASSWORD VARCHAR(30),
EMAIL VARCHAR(50)
);

DROP TABLE IF EXISTS OCR_INFO;
CREATE TABLE OCR_INFO (
	
	OCR_REQUEST_ID VARCHAR PRIMARY KEY,
	GI_VISION_RESPONSE VARCHAR,
	CROWD_SOURCE_RESPONSE VARCHAR,
	ABZOOBA_REQUEST_INFO VARCHAR,
	ABZOOBA_REQUEST_RESPONSE VARCHAR,
	CLOUD_SOURCE_USER_ID VARCHAR,
	STATUS VARCHAR,
	IMAGE_URL VARCHAR,
	IMAGE BLOB,
	IMAGE_UPLOAD_DATE DATE,
	IMAGE_PROCESSED_DATE DATE,
	CROWD_SOURCE_SUBMIT_DATE DATE	
);
